{{- if .Values.certManager.acmeDNS.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: '{{ .Values.certManager.acmeDNS.secretName }}'
  namespace: '{{ .Release.Namespace }}'
type: Opaque
stringData:
  {{ .Values.certManager.acmeDNS.secretKey }}: >
    {
      "fullDomain": "{{ .Values.certManager.acmeDNS.fullDomain }}",
      "subDomain": "{{ .Values.certManager.acmeDNS.subDomain }}",
      "username": "{{ .Values.certManager.acmeDNS.username }}",
      "password": "{{ .Values.certManager.acmeDNS.password }}"
    }
{{- end }}
