apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.certManager.clusterIssuer | quote }}
spec:
  acme:
    email: {{ .Values.certManager.email | quote }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: {{ .Values.certManager.privateKeySecretName | quote }}
    solvers:
      - dns01:
          acmeDNS:
            host: {{ .Values.certManager.acmeDNS.host | quote }}
            accountSecretRef:
              name: {{ .Values.certManager.acmeDNS.secretName | quote }}
              key: {{ .Values.certManager.acmeDNS.secretKey | quote }}
