{{- if and .Values.ingress.parentIngressClass.enabled (not (lookup "networking.k8s.io/v1" "IngressClass" "" .Values.ingress.className)) }}
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: {{ .Values.ingress.className | quote }}
spec:
  controller: k8s.io/ingress-nginx
{{- end }}