{{- if .Values.redirect.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: latencylab-redirect
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: {{ .Values.ingress.className | quote }}
  tls:
    - hosts:
        {{- range .Values.redirect.hosts }}
        - {{ . }}
        {{- end }}
      secretName: {{ .Values.redirect.tlsSecretName }}
  rules:
    {{- range .Values.redirect.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-redirect
                port:
                  number: 80
    {{- end }}
  {{- end }}
