{{- if .Values.redirect.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: nginx-redirect
  namespace: {{ .Release.Namespace }}
spec:
  type: LoadBalancer
  {{- if .Values.ingress.controller.service.loadBalancerIPFile }}
  loadBalancerIP: {{ .Files.Get (printf "files/%s" .Values.ingress.controller.service.loadBalancerIPFile) | trim | quote }}
  {{- end }}
  selector:
    app: nginx-redirect
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  {{- end }}
